In [ ]:
import pandas as pd

In [ ]:
df_precios = pd.read_csv('Gold Price Prediction.csv')
df_precios.head(100)

,Date,Price 2 Days Prior,Price 1 Day Prior,Price Today,Price Tomorrow,Price Change Tomorrow,Price Change Ten,Std Dev 10,Twenty Moving Average,Fifty Day Moving Average,...,Monthly Inflation Rate,EFFR Rate,Volume,Treasury Par Yield Month,Treasury Par Yield Two Year,Treasury Par Yield Curve Rates (10 Yr),DXY,SP Open,VIX,Crude
0,8/7/24,2405.87,2384.90,2385.83,NaN,NaN,NaN,30.155078,2414.7450,2368.2948,...,3.0,5.33,96,5.50,4.00,3.96,103.37,5293.13,24.77,72.84
1,8/6/24,2442.74,2405.87,2384.90,2385.83,0.93,NaN,29.423936,2414.1525,2367.7916,...,3.0,5.33,89,5.50,3.99,3.90,102.78,5206.42,33.71,73.86
2,8/5/24,2447.17,2442.74,2405.87,2384.90,-20.97,NaN,28.341301,2413.2305,2367.1584,...,3.0,5.33,86,5.52,3.89,3.78,103.22,5151.14,23.39,74.21
3,8/2/24,2447.23,2447.17,2442.74,2405.87,-36.87,NaN,28.616661,2411.0920,2365.7250,...,3.0,5.33,89,5.54,3.88,3.80,104.31,5376.63,20.52,76.87
4,8/1/24,2411.09,2447.23,2447.17,2442.74,-4.43,NaN,26.084796,2408.5670,2363.5624,...,3.0,5.33,83,5.55,4.16,3.99,104.07,5537.84,16.20,78.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3/25/24,2181.81,2165.64,2173.10,2179.72,6.62,181.76,14.958991,2140.0655,2070.7254,...,3.5,5.33,85,5.51,4.54,4.25,104.43,5219.52,13.67,80.85
96,3/22/24,2204.04,2181.81,2165.64,2173.10,7.46,173.30,15.611817,2132.9730,2068.3512,...,3.5,5.33,91,5.51,4.59,4.22,103.99,5242.48,12.92,80.84
97,3/21/24,2157.16,2204.04,2181.81,2165.64,-16.17,148.12,15.713669,2126.4695,2066.0182,...,3.5,5.33,93,5.51,4.62,4.27,103.24,5253.43,12.98,81.49
98,3/20/24,2161.98,2157.16,2204.04,2181.81,-22.23,84.98,15.546050,2118.6290,2063.0840,...,3.5,5.33,91,5.50,4.59,4.27,103.84,5181.69,13.83,83.20
99,3/19/24,2156.08,2161.98,2157.16,2204.04,46.88,140.45,11.455593,2109.7210,2059.5398,...,3.5,5.33,89,5.52,4.68,4.30,103.59,5139.09,14.50,82.85

In [ ]:
df_precios.dtypes

Date                                       object
Price 2 Days Prior                        float64
Price 1 Day Prior                         float64
Price Today                               float64
Price Tomorrow                            float64
Price Change Tomorrow                     float64
Price Change Ten                          float64
Std Dev 10                                float64
Twenty Moving Average                     float64
Fifty Day Moving Average                  float64
200 Day Moving Average                    float64
Monthly Inflation Rate                    float64
EFFR Rate                                 float64
Volume                                      int64
Treasury Par Yield Month                  float64
Treasury Par Yield Two Year               float64
Treasury Par Yield Curve Rates (10 Yr)    float64
DXY                                       float64
SP Open                                   float64
VIX                                       float64
Crude                                     float64
dtype: object

In [ ]:
DatosFaltantes=df_precios.isna().sum()
DatosFaltantes

Date                                       0
Price 2 Days Prior                         0
Price 1 Day Prior                          0
Price Today                                0
Price Tomorrow                             1
Price Change Tomorrow                      1
Price Change Ten                          10
Std Dev 10                                 9
Twenty Moving Average                      0
Fifty Day Moving Average                   0
200 Day Moving Average                     0
Monthly Inflation Rate                     0
EFFR Rate                                  0
Volume                                     0
Treasury Par Yield Month                   0
Treasury Par Yield Two Year                0
Treasury Par Yield Curve Rates (10 Yr)     0
DXY                                        0
SP Open                                    0
VIX                                        0
Crude                                      0
dtype: int64

In [ ]:
ListaValNum = ["Price Tomorrow","Price Change Tomorrow","Price Change Ten","Std Dev 10"]
for col in ListaValNum:
 df_precios[col] = df_precios[col].fillna(df_precios[col].mean())

In [ ]:
DatosFaltantes=df_precios.isna().sum()
DatosFaltantes

Date                                      0
Price 2 Days Prior                        0
Price 1 Day Prior                         0
Price Today                               0
Price Tomorrow                            0
Price Change Tomorrow                     0
Price Change Ten                          0
Std Dev 10                                0
Twenty Moving Average                     0
Fifty Day Moving Average                  0
200 Day Moving Average                    0
Monthly Inflation Rate                    0
EFFR Rate                                 0
Volume                                    0
Treasury Par Yield Month                  0
Treasury Par Yield Two Year               0
Treasury Par Yield Curve Rates (10 Yr)    0
DXY                                       0
SP Open                                   0
VIX                                       0
Crude                                     0
dtype: int64

Modelo predictivo

In [ ]:
from google.colab import files


df_precios.to_csv('datos.csv', index=False)

# Descargar el archivo
files.download('datos.csv')